name: Hosted Notebooks Samples Check

on:
  pull_request:
    branches: 
      - feature/samples-gallery
env:
  pipelineVars: '{''optHash'': ''${{ github.sha }}'', ''githubRepo'': ''${{ github.repository }}'', ''prCommitHash'': ''${{ github.event.pull_request.head.sha }}'', ''isGithubPrBuild'': ''true'' }'

jobs:
  build:
    name: Call Azure Pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Azure Pipelines Action
        uses: Azure/pipelines@v1.2
        with:
          azure-devops-project-url: ${{ secrets.QUANTUM_PROGRAM_ADO_URL }}
          azure-pipeline-name:  ${{ secrets.HOSTED_NOTEBOOKS_PIPELINE_NAME }}
          azure-devops-token: ${{ secrets.HOSTED_NOTEBOOKS_PIPELINE_ADO_PAT }}
          azure-pipeline-variables: ${{ env.pipelineVars }}
